import { FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import Plot from "react-plotly.js";
import { api, Experiment, Pilot, Progress, Run, Verification } from "./api";

type Tab = "config" | "hypothesis" | "plan" | "execution" | "aed" | "factorial";
const tabs: Array<{ id: Tab; label: string; icon: string }> = [
  { id: "config", label: "Configuração", icon: "01" }, { id: "hypothesis", label: "Hipótese", icon: "02" },
  { id: "plan", label: "Plano", icon: "03" }, { id: "execution", label: "Execução", icon: "04" },
  { id: "aed", label: "AED", icon: "05" }, { id: "factorial", label: "Fatorial", icon: "06" },
];

const decimal = (value: number | null | undefined, digits = 3) => value == null ? "—" : value.toFixed(digits).replace(".", ",");
const pct = (value: number | null | undefined) => value == null ? "—" : `${value.toFixed(2).replace(".", ",")} %`;

function Field({ label, value, onChange, type = "number", min, step }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; min?: number; step?: number }) {
  return <label className="field"><span>{label}</span><input type={type} value={value} min={min} step={step} onChange={(event) => onChange(event.target.value)} /></label>;
}

function App() {
  const [activeTab, setActiveTab] = useState<Tab>("config");
  const [experiment, setExperiment] = useState<Experiment | null>(null);
  const [hypothesis, setHypothesis] = useState("A maior capacidade de atendimento reduz a espera média na fila.");
  const [plan, setPlan] = useState<Run[]>([]);
  const [progress, setProgress] = useState<Progress>({ running: false, completed: 0, total: 0 });
  const [verification, setVerification] = useState<Verification | null>(null);
  const [pilot, setPilot] = useState<Pilot | null>(null);
  const [message, setMessage] = useState("");
  const [config, setConfig] = useState({ replicas: 10, n_clients: 50000, warmup: 1000, service_mean: 1, seed_experiment: 20260922, seed_order: 20260923 });
  const [pilotConfig, setPilotConfig] = useState({ n_clients: 1000, warmup: 100, replicas: 10, short_clients: 300, welch_clients: 300, welch_replicas: 10, welch_window: 25 });

  const planQuery = useQuery({ queryKey: ["plan", experiment?.id], queryFn: () => api.getPlan(experiment!.id), enabled: Boolean(experiment?.id) && plan.length === 0 });
  useEffect(() => { if (planQuery.data) setPlan(planQuery.data); }, [planQuery.data]);

  useEffect(() => {
    if (!experiment || !progress.running) return;
    const source = new EventSource(`${apiUrl()}/api/experiments/${experiment.id}/events`);
    source.addEventListener("progresso", (event) => setProgress(JSON.parse((event as MessageEvent).data) as Progress));
    source.onerror = () => source.close();
    return () => source.close();
  }, [experiment, progress.running]);

  const updateConfig = (key: keyof typeof config) => (value: string) => setConfig((current) => ({ ...current, [key]: Number(value) }));
  const updatePilot = (key: keyof typeof pilotConfig) => (value: string) => setPilotConfig((current) => ({ ...current, [key]: Number(value) }));
  const rho = config.n_clients ? 0.9 / 1 : 0.9;
  const create = useMutation({ mutationFn: () => api.createExperiment(config), onSuccess: (created) => { setExperiment(created); setMessage(`Experimento #${created.id} criado.`); setActiveTab("hypothesis"); }, onError: showError });
  const save = useMutation({ mutationFn: () => api.saveHypothesis(experiment!.id, hypothesis), onSuccess: (updated) => { setExperiment(updated); setMessage("Hipótese registrada antes da execução."); setActiveTab("plan"); }, onError: showError });
  const build = useMutation({ mutationFn: () => api.createPlan(experiment!.id), onSuccess: (rows) => { setPlan(rows); setMessage(`${rows.length} corridas planejadas em ordem aleatória.`); setActiveTab("execution"); }, onError: showError });
  const verify = useMutation({ mutationFn: () => api.verify({ n_clients: 1000, warmup: 100, replicas: 2, workers: 1 }), onSuccess: (result) => { setVerification(result); setMessage("Verificação concluída."); }, onError: showError });
  const runPilot = useMutation({ mutationFn: () => api.pilot(pilotConfig), onSuccess: (result) => { setPilot(result); setMessage("AED piloto concluída. Ela permanece separada do fatorial."); }, onError: showError });

  function showError(error: Error) { setMessage(error.message); }
  function submit(event: FormEvent) { event.preventDefault(); create.mutate(); }
  function apiUrl() { return import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000"; }
  function start() { if (!experiment) return; setProgress({ running: true, completed: 0, total: plan.length }); api.start(experiment.id, 1).catch(showError); }
  function cancel() { if (experiment) api.cancel(experiment.id).then(() => setMessage("Cancelamento solicitado.")).catch(showError); }
  function retry() { if (experiment) { setProgress((current) => ({ ...current, running: true })); api.retry(experiment.id, 1).catch(showError); } }

  const completed = progress.total > 0 ? Math.round(progress.completed / progress.total * 100) : 0;
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">2³</span><div><strong>Experimentos</strong><small>plataforma de filas</small></div></div><div className="sidebar-caption">Fluxo do estudo</div><nav>{tabs.map((tab) => <button key={tab.id} className={activeTab === tab.id ? "nav-item active" : "nav-item"} onClick={() => setActiveTab(tab.id)} disabled={tab.id === "factorial"}><span className="nav-index">{tab.icon}</span><span>{tab.label}</span>{tab.id === "factorial" && <span className="lock">⌑</span>}</button>)}</nav><div className="sidebar-foot"><span className="status-dot" /> API conectada<br /><small>pt-BR · unidade: minutos</small></div></aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">ESTUDO FATORIAL 2³</span><h1>Planejar, executar, aprender</h1></div><div className="top-meta"><span className="pill">M/M/c · FIFO</span>{experiment && <span className="experiment-id">EXP-{String(experiment.id).padStart(4, "0")}</span>}</div></header>
      {message && <div className="notice" role="status"><span>●</span>{message}<button onClick={() => setMessage("")} aria-label="Fechar mensagem">×</button></div>}
      {activeTab === "config" && <section className="content"><SectionHeading eyebrow="01 / desenho" title="Configure o experimento" description="Defina o tamanho das corridas e preserve as sementes que tornam cada resultado reproduzível." /><form onSubmit={submit} className="config-layout"><div className="panel form-panel"><div className="panel-label">Parâmetros da corrida</div><div className="fields-grid"><Field label="Réplicas (r)" value={config.replicas} min={10} onChange={updateConfig("replicas")} /><Field label="Clientes (N)" value={config.n_clients} min={2} onChange={updateConfig("n_clients")} /><Field label="Aquecimento (W)" value={config.warmup} min={0} onChange={updateConfig("warmup")} /><Field label="Média do serviço (min)" value={config.service_mean} step={0.1} onChange={updateConfig("service_mean")} /></div><div className="divider" /><div className="panel-label">Sementes do experimento</div><div className="fields-grid"><Field label="Semente das corridas" value={config.seed_experiment} onChange={updateConfig("seed_experiment")} /><Field label="Semente da ordem" value={config.seed_order} onChange={updateConfig("seed_order")} /></div><button className="primary" type="submit" disabled={create.isPending}>{create.isPending ? "Criando..." : "Criar experimento"}<span>→</span></button></div><div className="panel factor-panel"><div className="panel-label">Fatores e estabilidade</div><div className="factor-row"><span className="factor-letter">A</span><div><strong>Servidores</strong><small>níveis: 1 · 2</small></div></div><div className="factor-row"><span className="factor-letter amber">B</span><div><strong>Taxa de chegada λ</strong><small>níveis: 0,5 · 0,9 clientes/min</small></div></div><div className="factor-row"><span className="factor-letter coral">C</span><div><strong>Serviço</strong><small>exponencial · constante</small></div></div><div className="rho-box"><span>ρ máximo previsto</span><strong>{decimal(rho, 2)}</strong><small>válido: ρ &lt; 1 em todas as células</small></div></div></form></section>}
      {activeTab === "hypothesis" && <section className="content narrow"><SectionHeading eyebrow="02 / antes da execução" title="Registre a hipótese" description="A hipótese será bloqueada com marca temporal quando a primeira corrida começar." /><div className="panel hypothesis-card"><label className="field"><span>Hipótese do experimento</span><textarea value={hypothesis} onChange={(event) => setHypothesis(event.target.value)} disabled={Boolean(experiment?.hypothesis_id)} /></label><div className="hypothesis-footer"><span className={experiment?.hypothesis_id ? "locked-badge" : "draft-badge"}>{experiment?.hypothesis_id ? "Hipótese registrada" : "Rascunho editável"}</span><button className="primary" onClick={() => save.mutate()} disabled={!experiment || save.isPending || Boolean(experiment.hypothesis_id)}>{save.isPending ? "Registrando..." : "Registrar hipótese"}<span>→</span></button></div></div><div className="method-note"><strong>Por que aqui?</strong><span>O texto fica fixado antes de qualquer corrida. A AED posterior descreve a resposta, mas não compara níveis nem estima efeitos.</span></div></section>}
      {activeTab === "plan" && <section className="content"><SectionHeading eyebrow="03 / aleatorização" title="Plano de corridas" description="Oito células, sinais codificados e uma ordem de execução sorteada por semente própria." /><div className="toolbar"><button className="primary" onClick={() => build.mutate()} disabled={!experiment || build.isPending}>{build.isPending ? "Gerando..." : "Gerar plano"}<span>↗</span></button><span className="toolbar-note">{plan.length ? `${plan.length} corridas · ordem reproduzível` : "A hipótese precisa estar registrada"}</span></div>{plan.length > 0 && <RunTable rows={plan.slice(0, 16)} />}</section>}
      {activeTab === "execution" && <section className="content"><SectionHeading eyebrow="04 / observação" title="Execute com rastreabilidade" description="Cada réplica é uma corrida completa, com sistema vazio e uma semente independente." /><div className="execution-grid"><div className="panel execution-card"><div className="run-orbit"><div className="orbit-center">{completed}<small>%</small></div><div className="orbit-ring" style={{ background: `conic-gradient(var(--teal) ${completed}%, var(--line) 0)` }} /></div><div className="execution-copy"><span className="panel-label">Estado da execução</span><h2>{progress.running ? "Corridas em andamento" : experiment?.status === "concluido" ? "Experimento concluído" : "Pronto para executar"}</h2><p>{progress.completed} de {progress.total || plan.length || 80} corridas concluídas.</p><div className="button-row"><button className="primary" onClick={start} disabled={!experiment || !plan.length || progress.running}>Iniciar corridas <span>▶</span></button><button className="ghost" onClick={cancel} disabled={!progress.running}>Cancelar</button><button className="ghost" onClick={retry} disabled={progress.running || experiment?.status !== "cancelado"}>Reintentar</button></div></div></div><div className="panel rule-card"><div className="panel-label">Regras preservadas</div><ul><li><b>80</b> corridas completas</li><li><b>PCG64</b> + SeedSequence.spawn</li><li><b>W = 1.000</b> clientes descartados</li><li><b>média por corrida</b> como unidade</li></ul></div></div></section>}
      {activeTab === "aed" && <section className="content"><SectionHeading eyebrow="05 / piloto exploratório" title="AED antes do fatorial" description="Uma configuração exigente para entender a resposta, o aquecimento e o tamanho da corrida." /><div className="aed-layout"><div className="panel form-panel"><div className="panel-label">Piloto rápido para explorar</div><div className="fields-grid"><Field label="Clientes (N)" value={pilotConfig.n_clients} min={20} onChange={updatePilot("n_clients")} /><Field label="Aquecimento (W)" value={pilotConfig.warmup} min={1} onChange={updatePilot("warmup")} /><Field label="Réplicas" value={pilotConfig.replicas} min={3} onChange={updatePilot("replicas")} /><Field label="Réplicas Welch" value={pilotConfig.welch_replicas} min={2} onChange={updatePilot("welch_replicas")} /></div><button className="primary" onClick={() => runPilot.mutate()} disabled={runPilot.isPending}>{runPilot.isPending ? "Calculando..." : "Executar AED piloto"}<span>↗</span></button></div>{pilot ? <PilotResult result={pilot} /> : <div className="empty-state"><span className="empty-icon">∿</span><strong>Nenhum piloto nesta sessão</strong><span>Os gráficos e diagnósticos aparecerão aqui.</span></div>}</div><div className="toolbar"><button className="secondary" onClick={() => verify.mutate()} disabled={verify.isPending}>{verify.isPending ? "Verificando..." : "Verificar simulador contra teoria"}</button>{verification && <span className={verification.passed ? "success-text" : "warning-text"}>Erro máximo: {pct(verification.max_relative_error_pct)} · {verification.passed ? "critério atendido" : "revisar tamanho da corrida"}</span>}</div>{verification && <VerificationChart result={verification} />}</section>}
      {activeTab === "factorial" && <section className="content narrow"><SectionHeading eyebrow="06 / bloqueado" title="Análise factorial" description="A análise será habilitada quando as 80 corridas completas estiverem disponíveis." /><div className="locked-panel"><span className="lock-large">⌑</span><h2>Ainda não liberado</h2><p>O piloto não estima efeitos. Primeiro conclua todas as combinações e réplicas do experimento.</p><div className="locked-progress"><span style={{ width: `${Math.min(100, plan.length / 80 * 100)}%` }} /></div><small>{plan.length} / 80 corridas disponíveis</small></div></section>}
    </main>
  </div>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div>; }
function RunTable({ rows }: { rows: Run[] }) { return <div className="table-wrap"><table><thead><tr><th>Ordem</th><th>Corrida</th><th>Célula</th><th>Réplica</th><th>A</th><th>B</th><th>C</th><th>ρ</th><th>Estado</th></tr></thead><tbody>{rows.map((row) => <tr key={row.run_id}><td className="mono">{row.execution_order}</td><td className="mono">{row.run_id}</td><td>{row.cell}</td><td>{row.replica}</td><td>{row.factor_a > 0 ? "+" : "−"}</td><td>{row.factor_b > 0 ? "+" : "−"}</td><td>{row.factor_c > 0 ? "+" : "−"}</td><td>{decimal(row.rho, 2)}</td><td><span className="state">{row.state}</span></td></tr>)}</tbody></table><div className="table-foot">Mostrando {rows.length} corridas do plano · exportação CSV disponível pela API</div></div>; }
function PilotResult({ result }: { result: Pilot }) { return <div className="panel result-panel"><div className="result-header"><div><span className="panel-label">Resumo da AED</span><h3>Média {decimal(result.summary.mean)} min</h3></div><span className="pilot-badge">PILOTO · SEPARADO</span></div><div className="metric-grid"><Metric label="CV" value={pct(result.summary.cv_pct)} /><Metric label="Shapiro p" value={decimal(result.summary.shapiro_p, 3)} /><Metric label="ln Shapiro p" value={decimal(result.summary.log_shapiro_p, 3)} /><Metric label="lag-1" value={decimal(result.summary.lag1_correlation, 2)} /></div><p className="warning-line">ⓘ {result.summary.normality_warning}</p><Plot data={[{ x: result.individual_waits.acf.map((_, index) => index), y: result.individual_waits.acf, type: "scatter", mode: "lines", line: { color: "#0e7c7b" } }]} layout={{ autosize: true, height: 210, margin: { l: 42, r: 12, t: 12, b: 38 }, paper_bgcolor: "transparent", plot_bgcolor: "transparent", xaxis: { title: { text: "Defasagem" } }, yaxis: { title: { text: "ACF" } }, font: { family: "IBM Plex Mono", size: 10, color: "#496169" } }} useResizeHandler style={{ width: "100%" }} config={{ displayModeBar: false, responsive: true }} /></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function VerificationChart({ result }: { result: Verification }) { return <div className="chart-panel"><Plot data={[{ x: result.cells.map((cell) => `C${cell.cell}`), y: result.cells.map((cell) => cell.simulated), type: "bar", marker: { color: result.cells.map((cell) => cell.status === "verificado" ? "#0e7c7b" : "#c6a15b") } }]} layout={{ autosize: true, height: 300, margin: { l: 55, r: 18, t: 35, b: 50 }, title: { text: "Espera média simulada por célula" }, xaxis: { title: { text: "Célula" } }, yaxis: { title: { text: "Espera (min)" } }, paper_bgcolor: "transparent", plot_bgcolor: "transparent", font: { family: "IBM Plex Mono", size: 10, color: "#496169" } }} useResizeHandler style={{ width: "100%" }} config={{ displayModeBar: false, responsive: true }} /></div>; }

export default App;